{% set name = "chemex" %}
{% set version = "2022.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: 996343df04afb3614ba0505472baad024457d5db6b401c600ca2683b88c3f17e

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9,<3.11
    - pip
    - poetry-core
  run:
    - python >=3.9,<3.11
    - cachetools
    - lmfit
    - matplotlib-base
    - numpy
    - pydantic
    - rapidfuzz
    - rich
    - scipy
    - tomli

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip

about:
  home: http://gbouvignies.github.io/ChemEx/
  summary: ChemEx is an analysis program for chemical exchange detected by NMR
  license: GPL-3.0-only
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - gbouvignies
