{% set name = "chemex" %}
{% set version = "2018.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 018d7fddbbef1bbe4b12efcc24dcf92477d6108f439a0ffbd2d5956c386a0ae4

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - chemex = chemex.chemex:main

requirements:
  host:
    - python >=3.5
    - setuptools_scm
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - matplotlib-base
    - lmfit
    - asteval

test:
  imports:
    - chemex

about:
  home: http://github.com/gbouvignies/chemex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ChemEx is an analysis program for chemical exchange detected by NMR.
  description: |
    ChemEx is an analysis program for chemical exchange detected by NMR.
    It is designed to take almost any kind of NMR data to aid the analysis,
    but the principle techniques are CPMG relaxation dispersion and Chemical
    Exchange Saturation Transfer.
  dev_url: https://github.com/gbouvignies/chemex

extra:
  recipe-maintainers:
    - gbouvignies
