{% set name = "chemex" %}
{% set version = "2022.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: 33b0c0ba553b097a7d84acb056a1dbf414ccd60375abe8f1f2687ab80dcc9f24

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.11
    - pip
  run:
    - python >=3.6,<3.11
    - cachetools >=5.2.0,<6.0.0
    - lmfit >=1.0.3,<2.0.0
    - matplotlib-base >=3.5.3,<4.0.0
    - numpy >=1.23.3,<2.0.0
    - pydantic >=1.10.2,<2.0.0
    - rapidfuzz >=2.8.0,<3.0.0
    - rich >=12.5.1,<13.0.0
    - scipy >=1.9.1,<2.0.0
    - tomli >=2.0.1,<3.0.0

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip

about:
  home: http://gbouvignies.github.io/ChemEx/
  summary: ChemEx is an analysis program for chemical exchange detected by NMR
  license: GPL-3.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gbouvignies