travis:
  secure:
    BINSTAR_TOKEN: Fdft0fYWaN2aARffYNCTfSzJvSIuBKDo82U4wrCoDSjI7BwTzOcezIVB0IzgWaTzeeB4Xf3s+4i0X81cZzayv53xYAzKsTvZGmYeSYKwBHMipehg4r+526RGe9l4sIjI0bEXRxhkBpBQRvlg0RWQ7qb0GzgfDEQ9DnndH2d48L8q5/Ch2S/oqSH971ANYPutly7VxDtcNWBdc4zdBP+y/c5yzWIm+Kxu1zGA7T0ZHkDLyoAzBOfvCFPZ9weUKm0+ADtTjTqsBrJwro+v3uVSkbcxM7IZ03CMbyuhbR89iisbkbUo97Y2PjvsA3b234jpMC8OZYMqLPN4CtFMoJ4HB+oZnCYlY5wzeHsi5NF8xi+YHKYbnL9IVCzDFNdBAL6p+nFiWiXvJvFlTScQTQeaXkNvwt3cwcJy0vKgLMK8iuv9nnEx8QIofx5OT/XutP4L1EhzJxnQXi1FRk3i2Gzj5jalZighYXXaQVmRkaq849cT+S6PXNYu0Vbv7KuqCtuoQT3udvancUcpXRWjAYczxLZkMfK0GCCpTFSb6PWvE+wGKDABBLQwcsowXL5ZBQd/7yZKhewzNA4JQsVMbZvaHks2omYGWKImrgkY8craGUWp8DqWcNOIpvqlPITR8meVzLJI6FaASAdhyL4UjwS2Yvm9wK9sEmm3cc6bRSHYow4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
